export const categoryCounts = {
  acaibowls: 23,
  afghani: 16,
  african: 102,
  arabian: 6,
  arcades: 6,
  argentine: 41,
  artclasses: 4,
  artspacerentals: 2,
  asianfusion: 711,
  australian: 36,
  austrian: 17,
  bagels: 62,
  bakeries: 153,
  bangladeshi: 7,
  barbers: 2,
  bars: 1610,
  bartenders: 3,
  basque: 46,
  bbq: 529,
  beer_and_wine: 49,
  beerbar: 242,
  beergardens: 57,
  belgian: 35,
  beverage_stores: 9,
  bistros: 1,
  boating: 4,
  boattours: 2,
  bookstores: 4,
  bowling: 1,
  brasseries: 61,
  brazilian: 101,
  breakfast_brunch: 1333,
  breweries: 1,
  british: 56,
  bubbletea: 51,
  buffets: 104,
  burgers: 749,
  burmese: 3,
  butcher: 2,
  cabaret: 5,
  cafes: 388,
  cafeteria: 15,
  cajun: 124,
  cakeshop: 5,
  cambodian: 4,
  candy: 9,
  cantonese: 223,
  caribbean: 190,
  catalan: 3,
  catering: 61,
  champagne_bars: 2,
  cheese: 16,
  cheesesteaks: 20,
  chicken_wings: 331,
  chickenshop: 149,
  chimneycakes: 1,
  chinese: 1240,
  chocolate: 2,
  cocktailbars: 1861,
  coffee: 296,
  coffeeroasteries: 4,
  colombian: 8,
  comedyclubs: 4,
  comfortfood: 278,
  convenience: 15,
  cookingclasses: 3,
  cookingschools: 1,
  creperies: 47,
  cuban: 188,
  culturalcenter: 3,
  cupcakes: 2,
  customcakes: 1,
  czech: 6,
  danceclubs: 21,
  delis: 322,
  desserts: 371,
  dimsum: 366,
  diners: 148,
  dinnertheater: 17,
  divebars: 34,
  dominican: 89,
  donuts: 2,
  egyptian: 20,
  empanadas: 21,
  eritrean: 6,
  ethiopian: 63,
  eventplanning: 9,
  facepainting: 4,
  falafel: 85,
  farmersmarket: 1,
  festivals: 1,
  filipino: 92,
  fishnchips: 26,
  fitness: 1,
  fondue: 24,
  food: 3,
  food_court: 89,
  fooddeliveryservices: 40,
  foodstands: 172,
  foodtours: 2,
  foodtrucks: 124,
  french: 878,
  galleries: 5,
  gastropubs: 410,
  gelato: 5,
  georgian: 40,
  german: 71,
  giftshops: 1,
  gluten_free: 188,
  gourmet: 65,
  graphicdesign: 4,
  greek: 439,
  grocery: 90,
  hair: 2,
  haitian: 6,
  halal: 363,
  hawaiian: 95,
  headshops: 3,
  healthmarkets: 13,
  herbsandspices: 10,
  himalayan: 38,
  hkcafe: 40,
  homedecor: 2,
  honduran: 2,
  honey: 1,
  hookah_bars: 34,
  hotdog: 95,
  hotdogs: 214,
  hotpot: 176,
  hungarian: 11,
  icecream: 84,
  importedfood: 25,
  indonesian: 15,
  indoor_playcenter: 1,
  indpak: 524,
  intlgrocery: 8,
  irish: 112,
  irish_pubs: 98,
  italian: 2836,
  izakaya: 186,
  japacurry: 54,
  japanese: 1361,
  jazzandblues: 73,
  juicebars: 177,
  karaoke: 21,
  kebab: 30,
  kids_activities: 1,
  korean: 854,
  kosher: 131,
  laotian: 8,
  latin: 494,
  lebanese: 102,
  lounges: 292,
  macarons: 1,
  magicians: 2,
  malaysian: 88,
  markets: 3,
  meats: 11,
  mediterranean: 1296,
  mexican: 1088,
  mideastern: 385,
  modern_european: 86,
  mongolian: 6,
  moroccan: 87,
  movietheaters: 3,
  musicvenues: 34,
  newamerican: 2185,
  newmexican: 33,
  nonprofit: 2,
  noodles: 827,
  organic_stores: 2,
  pakistani: 28,
  panasian: 29,
  pancakes: 4,
  pastashops: 132,
  permanentmakeup: 2,
  persian: 55,
  personal_shopping: 2,
  peruvian: 160,
  petadoption: 3,
  petstore: 1,
  piadina: 1,
  pianobars: 40,
  pizza: 1274,
  poke: 117,
  polish: 22,
  poolhalls: 2,
  popuprestaurants: 16,
  popupshops: 1,
  portuguese: 45,
  poutineries: 10,
  pretzels: 17,
  publicmarkets: 9,
  pubs: 267,
  puertorican: 54,
  ramen: 486,
  raw_food: 44,
  restaurants: 58,
  russian: 56,
  salad: 596,
  salvadoran: 8,
  sandwiches: 733,
  sardinian: 2,
  scandinavian: 31,
  scottish: 2,
  seafood: 1412,
  seafoodmarkets: 21,
  senegalese: 30,
  shanghainese: 160,
  sharedofficespaces: 1,
  shavedice: 5,
  shoppingcenters: 5,
  sicilian: 11,
  singaporean: 44,
  slovakian: 2,
  smokehouse: 3,
  somali: 5,
  soulfood: 138,
  soup: 265,
  southafrican: 6,
  southern: 183,
  souvenirs: 1,
  spanish: 335,
  spas: 1,
  speakeasies: 15,
  sports_clubs: 9,
  sportsbars: 301,
  srilankan: 11,
  steak: 687,
  streetvendors: 62,
  supperclubs: 10,
  sushi: 978,
  szechuan: 230,
  tabletopgames: 2,
  tacos: 233,
  taiwanese: 119,
  tapas: 350,
  tapasmallplates: 691,
  tea: 31,
  teppanyaki: 13,
  "tex-mex": 60,
  thai: 803,
  theater: 9,
  themedcafes: 1,
  tikibars: 9,
  tobaccoshops: 3,
  tradamerican: 1218,
  trinidadian: 1,
  turkish: 206,
  tuscan: 46,
  ukrainian: 25,
  uzbek: 12,
  vegan: 364,
  vegetarian: 315,
  venezuelan: 32,
  venues: 411,
  vietnamese: 373,
  vintage: 5,
  waffles: 44,
  walkingtours: 1,
  wedding_planning: 2,
  whiskeybars: 39,
  wine_bars: 1145,
  womenscloth: 1,
  wraps: 18,
};

export const prices = ["$", "$$", "$$$", "$$$$"];

export const popularCategories = [
  { alias: "italian", title: "Italian", emoji: "🍝" },
  { alias: "newamerican", title: "American (New)", emoji: "🍔" },
  { alias: "cocktailbars", title: "Cocktail Bars", emoji: "🍸" },
  { alias: "bars", title: "Bars", emoji: "🍺" },
  { alias: "seafood", title: "Seafood", emoji: "🦞" },
  { alias: "japanese", title: "Japanese", emoji: "🍣" },
  { alias: "breakfast_brunch", title: "Breakfast & Brunch", emoji: "🍳" },
  { alias: "mediterranean", title: "Mediterranean", emoji: "🥙" },
  { alias: "pizza", title: "Pizza", emoji: "🍕" },
  { alias: "chinese", title: "Chinese", emoji: "🥡" },
  { alias: "tradamerican", title: "American (Traditional)", emoji: "🍗" },
  { alias: "wine_bars", title: "Wine Bars", emoji: "🍷" },
  { alias: "mexican", title: "Mexican", emoji: "🌮" },
  { alias: "sushi", title: "Sushi Bars", emoji: "🍣" },
  { alias: "french", title: "French", emoji: "🥐" },
  { alias: "korean", title: "Korean", emoji: "🍜" },
  { alias: "noodles", title: "Noodles", emoji: "🍜" },
  { alias: "thai", title: "Thai", emoji: "🍛" },
  { alias: "burgers", title: "Burgers", emoji: "🍔" },
  { alias: "sandwiches", title: "Sandwiches", emoji: "🥪" },
  { alias: "asianfusion", title: "Asian Fusion", emoji: "🍱" },
  { alias: "tapasmallplates", title: "Tapas/Small Plates", emoji: "🍤" },
  { alias: "steak", title: "Steakhouses", emoji: "🥩" },
  { alias: "salad", title: "Salad", emoji: "🥗" },
  { alias: "bbq", title: "Barbeque", emoji: "🍖" },
  { alias: "indpak", title: "Indian", emoji: "🍛" },
  { alias: "latin", title: "Latin American", emoji: "🌯" },
  { alias: "ramen", title: "Ramen", emoji: "🍜 " },
  { alias: "greek", title: "Greek", emoji: "🥙" },
  { alias: "venues", title: "Venues & Event Spaces", emoji: "🎉" },
  { alias: "gastropubs", title: "Gastropubs", emoji: "🍺" },
  { alias: "cafes", title: "Cafes", emoji: "☕" },
  { alias: "mideastern", title: "Middle Eastern", emoji: "🥙" },
  { alias: "vietnamese", title: "Vietnamese", emoji: "🍜" },
];
